### ISSUE TITLE
  Issue when the position is on the grid line in 'lat_lon_cwp_manipulation.R'

### ISSUE THREAD

**Issue by theotimefily** [OB7-IRD/furdeb#6]
Issue when the position is on one of the grid lines. Function duplicates the position for each possibilities. 

`  coord_mpt_latlong <- distinct(database_spatial_mpt_latlong[c("X","Y")])
  coord_mpt_latlong_cwp <- lat_lon_cwp_manipulation(manipulation_process = "lat_lon_to_cwp", 
                             data_longitude = as.character(coord_mpt_latlong$X), 
                             data_latitude = as.character(coord_mpt_latlong$Y), 
                             referential_grid_file_path = "C:/Users/2020tf001/Documents/Data_method_R/shapes/fao_cwp_grid/cwp-grid-map-10deg_x_10deg/cwp-grid-map-10deg_x_10deg.Rdata",
                             input_degree_format = "decimal_degree", 
                             epsg_code = 4326L, 
                             output_cwp_format = "corner_7" )
  
  tmp = coord_mpt_latlong_cwp %>%
    group_by(longitude_decimal_degree,
             latitude_decimal_degree) %>%
    mutate(count = n()) %>%
    filter(count != 1)`

[coord_mpt_latlong.csv](https://github.com/OB7-IRD/furdeb/files/11674709/coord_mpt_latlong.csv)

**Comment by MathieuDepetris** [comment]
Problem solved with update of the function process.
